# -*- coding: utf-8 -*-
"""Aggregate per-cell summary.json into DUO vs UniSO LaTeX/CSV (oracle y, higher better)."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

_PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))
import csv
import json
from dataclasses import dataclass
from typing import Any

from comparisonExperiment.experiment1.comparison_v4_protocol import (
    PHASES,
    SHIFTS,
    TOPK,
    comparison_out_dir,
    iter_cells,
)


@dataclass(frozen=True)
class RowScore:
    shift: str
    phase: str
    duo_topk_mean: float
    uniso_topk_mean: float
    duo_max: float
    uniso_max: float


def _metric_from_summary(summary_path: Path, method: str, key: str) -> float:
    if not summary_path.exists():
        return float("nan")
    rec = json.loads(summary_path.read_text(encoding="utf-8"))
    m = rec.get("methods", {}).get(method, {})
    if m.get("missing"):
        return float("nan")
    scores = m.get("scores", {})
    return float(scores.get(key, float("nan")))


def collect_rows(out_root: Path, bundle_root: Path, uniso_root: Path) -> list[RowScore]:
    rows: list[RowScore] = []
    for cell in iter_cells(bundle_root=bundle_root, uniso_root=uniso_root):
        cell_dir = comparison_out_dir(out_root, cell.shift, cell.phase)
        summ = cell_dir / "summary.json"
        rows.append(
            RowScore(
                shift=cell.shift,
                phase=cell.phase,
                duo_topk_mean=_metric_from_summary(summ, "duo_mt_text", "topk_mean"),
                uniso_topk_mean=_metric_from_summary(summ, "uniso", "topk_mean"),
                duo_max=_metric_from_summary(summ, "duo_mt_text", "max"),
                uniso_max=_metric_from_summary(summ, "uniso", "max"),
            )
        )
    return rows


def _fmt(v: float) -> str:
    if v != v:
        return "---"
    return f"{v:.4f}"


def _task_label(shift: str) -> str:
    esc = shift.replace("_", "\\_")
    return f"D\\_test\\_{esc}"


def write_latex(rows: list[RowScore], out_tex: Path, *, topk: int) -> None:
    lines = [
        "% Auto-generated by export_duo_uniso_comparison_table.py",
        f"% Oracle normalized y (higher better); topk_mean over top-{topk} candidates.",
        "\\begin{table}[t]",
        "\\centering",
        "\\small",
        f"\\caption{{Exp1 scene-aware comparison: DUO v4 \\texttt{{mt\\_text}} vs UniSO-T "
        f"(128 candidates each; top-{topk} mean oracle $y$, higher better).}}",
        "\\label{tab:exp1-duo-uniso-comparison}",
        "\\begin{tabular}{llrr}",
        "\\hline",
        "Task & Phase & DUO mt\\_text & UniSO-T \\\\",
        "\\hline",
    ]
    for r in rows:
        duo_s = _fmt(r.duo_topk_mean)
        uniso_s = _fmt(r.uniso_topk_mean)
        if r.duo_topk_mean == r.duo_topk_mean and r.uniso_topk_mean == r.uniso_topk_mean:
            if r.duo_topk_mean > r.uniso_topk_mean + 1e-9:
                duo_s = f"\\textbf{{{duo_s}}}"
            elif r.uniso_topk_mean > r.duo_topk_mean + 1e-9:
                uniso_s = f"\\textbf{{{uniso_s}}}"
        lines.append(
            f"{_task_label(r.shift)} & \\texttt{{{r.phase}}} & {duo_s} & {uniso_s} \\\\"
        )
    lines.extend(["\\hline", "\\end{tabular}", "\\end{table}", ""])
    out_tex.parent.mkdir(parents=True, exist_ok=True)
    out_tex.write_text("\n".join(lines), encoding="utf-8")


def write_csv(rows: list[RowScore], out_csv: Path) -> None:
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    with out_csv.open("w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(
            [
                "shift",
                "phase",
                "duo_topk_mean",
                "uniso_topk_mean",
                "duo_max",
                "uniso_max",
            ]
        )
        for r in rows:
            w.writerow(
                [
                    r.shift,
                    r.phase,
                    r.duo_topk_mean,
                    r.uniso_topk_mean,
                    r.duo_max,
                    r.uniso_max,
                ]
            )


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--out_root",
        type=str,
        default="results/comparison1/exp1_scene_v4",
    )
    ap.add_argument(
        "--bundle_root",
        type=str,
        default="results/quality_bundle_4",
    )
    ap.add_argument("--uniso_root", type=str, default="../UniSO")
    ap.add_argument("--topk", type=int, default=TOPK)
    args = ap.parse_args()
    duo_root = Path(__file__).resolve().parents[2]
    out_root = (duo_root / args.out_root).resolve()
    bundle_root = (duo_root / args.bundle_root).resolve()
    uniso_root = (duo_root / args.uniso_root).resolve()

    rows = collect_rows(out_root, bundle_root, uniso_root)
    table_dir = out_root / "analysis_table"
    write_csv(rows, table_dir / "duo_uniso_comparison.csv")
    write_latex(rows, table_dir / "duo_uniso_comparison.tex", topk=int(args.topk))
    print(f"[table] wrote {table_dir / 'duo_uniso_comparison.tex'}")


if __name__ == "__main__":
    main()
